deployments:
- name: taxi_local_data
  entrypoint: scripts/orchestrate.py:main_flow
  work_pool: 
    name: taxipool

- name: taxi_s3_data
  entrypoint: scripts/orchestrate_s3.py:main_flow_s3
  work_pool: 
    name: taxipool
